name: touchgrass_flutter
description: Touch-Gras Flutter Web App - Substance Use Disorder Recovery Tool

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase integration
  supabase_flutter: ^2.5.6
  
  # State management - Riverpod as per architecture
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Local storage for device ID and offline support
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Timer and duration utilities
  timer_builder: ^2.0.0
  duration: ^3.0.13
  
  # UI and animations
  confetti: ^0.7.0
  lottie: ^3.1.2
  
  # Web specific
  url_launcher: ^6.2.6
  
  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code generation for Riverpod
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  # Assets for celebrations and UI
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
    
  # Custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf