name: Deploy to Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      
      - name: Install Flutter dependencies
        run: cd flutter_app && flutter pub get
      
      - name: Run quick tests
        run: cd flutter_app && flutter test
      
      - name: Build Flutter for staging
        run: |
          cd flutter_app
          flutter build web --release \
            --dart-define=SUPABASE_URL="${{ secrets.STAGING_SUPABASE_URL }}" \
            --dart-define=SUPABASE_ANON_KEY="${{ secrets.STAGING_SUPABASE_ANON_KEY }}"
      
      - name: Deploy to Cloudflare Pages (Staging)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: touchgrass-staging
          directory: flutter_app/build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment PR with staging URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Staging deployment ready at: https://touchgrass-staging.pages.dev'
            })